apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: yolo
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None