apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: yolo

spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongodb
  template:
    metadata:
      labels:
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: '/data/db'
          env:
            - name: 'MONGO_INITDB_ROOT_USERNAME'
              value: oderotim

            - name: 'MONGO_INITDB_ROOT_PASSWORD'
              valueFrom:
                secretKeyRef:
                  name: dbpassword
                  key: DBPASSWORD
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc